.test-template: &test
  cache:
    paths:
      - vendor/ruby
  before_script:
    - gem install bundler --no-document
    - bundle config set --local path 'vendor/ruby'
    - bundle install -j $(nproc) --path vendor  # Install dependencies into ./vendor/ruby
    - ruby -v                                   # Print out ruby version for debugging
  script:
    - bundle exec rake test

rspec-2.5:
  image: "ruby:2.5"
  <<: *test

rspec-2.6:
  image: "ruby:2.6"
  <<: *test

rspec-2.7:
  image: "ruby:2.7"
  <<: *test

rspec-3.0:
  image: "ruby:3.0"
  <<: *test
